# Generated by Django 5.0.6 on 2026-04-18 20:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('departure_time', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('total_miles', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('total_on_duty_hours', models.FloatField()),
                ('total_days', models.IntegerField()),
                ('route_geometry', models.JSONField()),
                ('stops', models.JSONField()),
                ('segments', models.JSONField()),
                ('daily_logs', models.JSONField()),
                ('geocoded', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
